From da6d690973ac7dc8b955b37bec2d4ec6ef045158 Mon Sep 17 00:00:00 2001
From: fishyfriend <fishyfriend@users.noreply.github.com>
Date: Wed, 22 May 2019 02:49:59 -0400
Subject: [PATCH] patch Makefile for nix

---
 Makefile | 31 +++++++++++++++++--------------
 1 file changed, 17 insertions(+), 14 deletions(-)

diff --git a/Makefile b/Makefile
index 724d024..f885b15 100644
--- a/Makefile
+++ b/Makefile
@@ -62,10 +62,12 @@ OCAMLFIND_INSTFLAGS=
 DESTDIR=
 
 STDINCLUDES=$(LIBDIR)/caml
-STUBLIBDIR=$(LIBDIR)/stublibs
 CC=gcc
 CFLAGS+=-fPIC -Wall -I$(STDINCLUDES)
 
+LIBDESTDIR=${out}/lib/
+STUBLIBDESTDIR=$(LIBDESTDIR)/stublibs
+
 # Disable optimization for GCC >= 4.7
 GCC_VERSION=$(shell gcc -dumpversion)
 ifeq "4.7" "$(word 2, $(sort 4.7 $(GCC_VERSION)))"
@@ -73,7 +75,7 @@ ifeq "4.7" "$(word 2, $(sort 4.7 $(GCC_VERSION)))"
 endif
 
 NATIVEFLAGS=-DCAML_NAME_SPACE -DNATIVE_CODE \
-       -DTARGET_$(ARCH) -DSYS_$(SYSTEM)
+       -DTARGET_$(ARCH) -DSYS_$(SYSTEM) 
 RANLIB=ranlib
 
 
@@ -95,17 +97,18 @@ libdelimccopt.a: stacks-native.o delim_serialize.o
 delimcc.cmxa: delimcc.cmx
 	$(OCAMLMKLIB) -o delimcc -oc delimccopt -dllpath .  delimcc.cmx
 
-install:
-	if test -f dlldelimcc.so; then cp dlldelimcc.so $(STUBLIBDIR); fi
-	cp libdelimcc.a $(LIBDIR) && \
-	  cd $(LIBDIR) && $(RANLIB) libdelimcc.a
-	cp delimcc.cma delimcc.cmi $(LIBDIR)
-	if test -f dlldelimccopt.so; then \
-	  cp dlldelimccopt.so $(STUBLIBDIR); fi
-	if test -f libdelimccopt.a;  then \
-	  cp libdelimccopt.a $(LIBDIR); \
-	  cd $(LIBDIR) && $(RANLIB) libdelimccopt.a; fi
-	if test -f delimcc.cmxa; then cp delimcc.cmxa $(LIBDIR); fi
+#install:
+#	mkdir -p $(LIBDESTDIR) $(STUBLIBDESTDIR)
+#	if test -f dlldelimcc.so; then cp dlldelimcc.so $(STUBLIBDESTDIR); fi
+#	cp libdelimcc.a $(LIBDESTDIR) && \
+#	  cd $(LIBDESTDIR) && $(RANLIB) libdelimcc.a
+#	cp delimcc.cma delimcc.cmi $(LIBDESTDIR)
+#	if test -f dlldelimccopt.so; then \
+#	  cp dlldelimccopt.so $(STUBLIBDESTDIR); fi
+#	if test -f libdelimccopt.a;  then \
+#	  cp libdelimccopt.a $(LIBDESTDIR); \
+#	  cd $(LIBDESTDIR) && $(RANLIB) libdelimccopt.a; fi
+#	if test -f delimcc.cmxa; then cp delimcc.cmxa $(LIBDESTDIR); fi
 
 findlib-install: META dlldelimcc.so libdelimcc.a delimcc.cma delimcc.cmi \
 	dlldelimccopt.so libdelimccopt.a delimcc.cmxa delimcc.cmx delimcc.a delimcc.mli
@@ -124,7 +127,7 @@ delimcc.cmo: delimcc.cmi
 
 # When using GCC 4.7, add the flag -fno-ipa-sra
 stacks-native.o: stacks-native.c
-	$(CC) -c $(NATIVEFLAGS) $(CFLAGS) stacks-native.c
+	$(CC) -c $(NATIVEFLAGS) $(CFLAGS) -fno-ipa-sra -O0 stacks-native.c
 
 top:	libdelimcc.a delimcc.cma
 	$(OCAMLMKTOP) -o ocamltopcc delimcc.cma
-- 
2.18.1

