From f3f4640b743395a431020135a6abec4e1dc667e0 Mon Sep 17 00:00:00 2001
From: fishyfriend <fishyfriend@users.noreply.github.com>
Date: Fri, 17 May 2019 00:13:49 -0400
Subject: [PATCH] patch Makefile for nix

---
 Makefile | 25 ++++++++++++++-----------
 1 file changed, 14 insertions(+), 11 deletions(-)

diff --git a/Makefile b/Makefile
index 724d024..4dea672 100644
--- a/Makefile
+++ b/Makefile
@@ -62,10 +62,12 @@ OCAMLFIND_INSTFLAGS=
 DESTDIR=
 
 STDINCLUDES=$(LIBDIR)/caml
-STUBLIBDIR=$(LIBDIR)/stublibs
 CC=gcc
 CFLAGS+=-fPIC -Wall -I$(STDINCLUDES)
 
+LIBDESTDIR=${out}/lib
+STUBLIBDESTDIR=${out}/lib/stublibs
+
 # Disable optimization for GCC >= 4.7
 GCC_VERSION=$(shell gcc -dumpversion)
 ifeq "4.7" "$(word 2, $(sort 4.7 $(GCC_VERSION)))"
@@ -73,7 +75,7 @@ ifeq "4.7" "$(word 2, $(sort 4.7 $(GCC_VERSION)))"
 endif
 
 NATIVEFLAGS=-DCAML_NAME_SPACE -DNATIVE_CODE \
-       -DTARGET_$(ARCH) -DSYS_$(SYSTEM)
+       -DTARGET_$(ARCH) -DSYS_$(SYSTEM) 
 RANLIB=ranlib
 
 
@@ -96,16 +98,17 @@ delimcc.cmxa: delimcc.cmx
 	$(OCAMLMKLIB) -o delimcc -oc delimccopt -dllpath .  delimcc.cmx
 
 install:
-	if test -f dlldelimcc.so; then cp dlldelimcc.so $(STUBLIBDIR); fi
-	cp libdelimcc.a $(LIBDIR) && \
-	  cd $(LIBDIR) && $(RANLIB) libdelimcc.a
-	cp delimcc.cma delimcc.cmi $(LIBDIR)
+	mkdir -p $(LIBDESTDIR) $(STUBLIBDESTDIR)
+	if test -f dlldelimcc.so; then cp dlldelimcc.so $(STUBLIBDESTDIR); fi
+	cp libdelimcc.a $(LIBDESTDIR) && \
+	  cd $(LIBDESTDIR) && $(RANLIB) libdelimcc.a
+	cp delimcc.cma delimcc.cmi $(LIBDESTDIR)
 	if test -f dlldelimccopt.so; then \
-	  cp dlldelimccopt.so $(STUBLIBDIR); fi
+	  cp dlldelimccopt.so $(STUBLIBDESTDIR); fi
 	if test -f libdelimccopt.a;  then \
-	  cp libdelimccopt.a $(LIBDIR); \
-	  cd $(LIBDIR) && $(RANLIB) libdelimccopt.a; fi
-	if test -f delimcc.cmxa; then cp delimcc.cmxa $(LIBDIR); fi
+	  cp libdelimccopt.a $(LIBDESTDIR); \
+	  cd $(LIBDESTDIR) && $(RANLIB) libdelimccopt.a; fi
+	if test -f delimcc.cmxa; then cp delimcc.cmxa $(LIBDESTDIR); fi
 
 findlib-install: META dlldelimcc.so libdelimcc.a delimcc.cma delimcc.cmi \
 	dlldelimccopt.so libdelimccopt.a delimcc.cmxa delimcc.cmx delimcc.a delimcc.mli
@@ -124,7 +127,7 @@ delimcc.cmo: delimcc.cmi
 
 # When using GCC 4.7, add the flag -fno-ipa-sra
 stacks-native.o: stacks-native.c
-	$(CC) -c $(NATIVEFLAGS) $(CFLAGS) stacks-native.c
+	$(CC) -c $(NATIVEFLAGS) $(CFLAGS) -fno-ipa-sra -O0 stacks-native.c
 
 top:	libdelimcc.a delimcc.cma
 	$(OCAMLMKTOP) -o ocamltopcc delimcc.cma
-- 
2.18.1

